Update pre_install

diff --git a/scripts/pre_install b/scripts/pre_install
--- a/scripts/pre_install
+++ b/scripts/pre_install
@@ -13,4 +13,16 @@ if [[ -n  $isProcRunning ]]; then
 fi
 # add delay of 10 seconds for supervisor to shut down completely before next installation steps runs
 sleep 10
+
+#rename target folder by appending current datetime to it
+datetimeval=$(date +%m%d%Y%H%M%S)
+targetpath=/home/ubuntu/pybossa/pybossa
+mv $targetpath $targetpath.$datetimeval
+rc=$?; if [[ $rc != 0 ]]; then
+echo "error renaming $targetpath to $targetpath.$datetimeval"
+exit $rc;
+else
+echo "renamed folder from $targetpath to $targetpath.$datetimeval"
+fi
+
 } >> /var/log/codedeploy-pre-install.log
